### ISSUE TITLE
youtube不能看 google不能登陆。

### ISSUE THREAD

**Issue by hehky** [justsweetpotato/web-proxy-heroku#1]
youtube不能看 google不能登陆。

**Comment by justsweetpotato** [comment]
Youtube 很多内容都是 JS 动态加载出来的, 并不能代理到.
推荐使用 You2Php 观看, https://github.com/justsweetpotato/you2php-heroku 

另外, 并不建议使用此项目登录任何账号, 并不安全.

最后, 如果有需要你可以使用这个公益机场, https://v2ray.dlolb.ml 将其添加到 V2RayN 等软件的订阅中并更新订阅即可使用.(此机场来源于网络, 安全性不做保证, 请注意)

**Comment by justsweetpotato** [comment]
你好, 你可能需要的是 jsproxy 这个项目,
地址: https://github.com/EtherDream/jsproxy
能满足你的需求, 功能更强大, 我打算换这个了 233.
